apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-local-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api-container
        image: backend-api-image:latest
        ports:
        - containerPort: 8080